### ISSUE TITLE
nse Py APIs not working as NSE shifted DNS to www1.nseindia.com

### ISSUE THREAD

**Issue by Mananssl01** [swapniljariwala/nsepy#113] opened 2020-01-04 13:44 UTC
nse Py APIs not working as NSE shifted DNS to www1.nseindia.com
effective from 4th Jan 2020.

**Comment by Bogaso** [comment] 2020-01-04 21:31
Thanks for let us know about this shift

**Comment by vaibhavsegat** [comment] 2020-01-05 13:55
Is there any fix for this?

**Comment by Cheko1** [comment] 2020-01-05 15:15
I tried to change the urls in 'live.py', 'liveurls.py' and 'urls.py' from www to www1, and clearing the cache. Still it is not working

**Comment by poseidon7908** [comment] 2020-01-07 03:50
Any fix for this? Would really appreciate it.

**Comment by malthesh88** [comment] 2020-01-07 09:19
Any fix for this issue?

**Comment by sf99167** [comment] 2020-01-08 02:24
Still no luck with access NSE website. I think they might have blocked this completely now. No HTML requests.....  Do let us know when there is a fix for this...

**Comment by daswanth500** [comment] 2020-01-09 13:54
It is still not working.. 9th Jan 2020. Any one having a solution for this?

**Comment by baluinfo86** [comment] 2020-01-10 17:06
hi - I tired your work around by updating urls.py and restarting the console, still facing the same issue.

**Comment by daswanth500** [comment] 2020-01-11 12:20
Yes, Im receiving this error = ConnectionError: ('Connection aborted.', OSError("(10053, 'WSAECONNABORTED')"))
Need to check again, the urls are able to retrieve data in browser, but when trying to do from python it is showing above error.

**Comment by subinoy** [comment] 2020-01-11 14:54
Guys you need to download the github repo and install by going into nsepy
folder and issue the command in a terminal python setup.py install.

That installation will work perfectly.
I also attached the screenshot of a working query.

[image: Screen Shot 2020-01-11 at 8.13.42 PM.png]

**Comment by malthesh88** [comment] 2020-01-11 18:35
> folder and issue the command in a terminal python setup.py install.

Can you please re-upload the image again? I tried running the file and got below error
![image](https://user-images.githubusercontent.com/17120189/72208953-9d904900-34c2-11ea-91a7-8f22045bc5f5.png)

**Comment by Praxal** [comment] 2020-01-11 18:35
@subinoy  If fresh installation of package after replacing 'urls.py' working for you?

**Comment by sf99167** [comment] 2020-01-14 02:37
Have tried all the recos mentioned above but no luck. Even a single power query for a single stock option chain is giving error. NSE has blocked all requests. Will try and connect with the NSE website team and ask for clarifications/workarounds today..

**Comment by subinoy** [comment] 2020-01-14 06:36
Hello Everyone,

Here I attached few screenshots which will help you to solve the issue with
nsepy installation.

1. You need to find this mail and link to the branch of the repo.

[image: Fix_repo.png]

2. When you will reach to the nsepy github by clicking only the above link
( this way it's easier to find) then click view files.
Look at the below pic. Don't download the Master branch. Look at the tree
of the branch start with 314.
[image: Fixed_repo.png]
3. Clone or download this branch of repo and cd to the nsepy-314 folder.

4. Issue the command python setup.py install

It should solve the problem with nsepy.

[image: Screen Shot 2020-01-14 at 11.52.41 AM.png]

Thanks
Subinoy

**Comment by poseidon7908** [comment] 2020-01-14 06:54
Subinoy, thanks but I cannot see any screenshot in the instructions that you just sent. Can you resend?

**Comment by subinoy** [comment] 2020-01-14 06:59
Try using Google Chrome.
Screenshots for visual guidance but just follow the instructions with the
below github repo branch.

https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4

Subinoy

**Comment by subinoy** [comment] 2020-01-14 07:18
> Subinoy, thanks but I cannot see any screenshot in the instructions that you just sent. Can you resend?

Did you see the email notice of my previous reply?

**Comment by poseidon7908** [comment] 2020-01-14 07:19
yes. Its working now. Thanks a lot.

**Comment by sf99167** [comment] 2020-01-14 07:23
made the changes in the .py files as mentioned on site. Its not working for me at least    
    On Tuesday, January 14, 2020, 12:49:41 PM GMT+5:30, poseidon7908 <notifications@github.com> wrote:  
 
 
yes. Its working now. Thanks a lot.

**Comment by nikunjpurohit** [comment] 2020-01-14 11:49
byte-compiling C:\Python33\Lib\site-packages\nsepy\urls.py to urls.cpython-33.pyc
  File "C:\Python33\Lib\site-packages\nsepy\urls.py", line 160
    headers = {**headers, **{'Referer': 'https://www1.nseindia.com/products/content/derivatives/equities/historical_fo.htm'}}
                ^
SyntaxError: invalid syntax

byte-compiling C:\Python33\Lib\site-packages\nsepy\__init__.py to __init__.cpython-33.pyc
running install_egg_info
Writing C:\Python33\Lib\site-packages\nsepy-0.7-py3.3.egg-info

Getting this error

**Comment by nikunjpurohit** [comment] 2020-01-14 12:16
File "C:\Python33\Lib\site-packages\nsepy\urls.py", line 160
headers = {**headers, **{'Referer': 'https://www1.nseindia.com/products/content/derivatives/equities/historical_fo.htm'}}
^
SyntaxError: invalid syntax
@subinoy  getting this error while using your files

**Comment by subinoy** [comment] 2020-01-14 13:06
use this repo to a fresh install.
https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4

**Comment by sf99167** [comment] 2020-01-14 13:12
Hi Subinoy
Somehow webscraping the option chain is not happenning. I guess its an NSE block??
regards
Sean

    On Tuesday, January 14, 2020, 06:36:32 PM GMT+5:30, Subinoy Biswas <notifications@github.com> wrote:  
 
 use this repo to a fresh install.
https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4

**Comment by subinoy** [comment] 2020-01-14 14:29
Post your code and error, otherwise difficult to understand what's wrong.
Subinoy

**Comment by sf99167** [comment] 2020-01-14 15:07
import requestsimport bs4import pandas as pdimport scipy import lxmlimport numpy
session = requests.Session()session.max_redirects = 60
from nsepy import get_historyfrom datetime import dateimport dateutil.relativedeltaimport matplotlib.pyplot as pltimport matplotlib
ACCStock=get_history(symbol="ACC", start=date(2018,1,1),end=date(2018,1,10))print(ACCStock)

    On Tuesday, January 14, 2020, 07:59:43 PM GMT+5:30, Subinoy Biswas <notifications@github.com> wrote:  
 
 Post your code and error, otherwise difficult to understand what's wrong.
Subinoy

**Comment by nikunjpurohit** [comment] 2020-01-14 15:23
File "C:\Python33\Lib\site-packages\nsepy\urls.py", line 160
headers = {**headers, **{'Referer': 'https://www1.nseindia.com/products/content/derivatives/equities/historical_fo.htm'}}

This line is giving "INVALID SYNTAX"error even in fresh install ... is your nsepy working now?

**Comment by subinoy** [comment] 2020-01-14 18:55
> import requestsimport bs4import pandas as pdimport scipy import lxmlimport numpy session = requests.Session()session.max_redirects = 60 from nsepy import get_historyfrom datetime import dateimport dateutil.relativedeltaimport matplotlib.pyplot as pltimport matplotlib ACCStock=get_history(symbol="ACC", start=date(2018,1,1),end=date(2018,1,10))print(ACCStock) 
-----------------------------------------------------------------
The code looking good to me. You didn't provide error what is coming with this code.

But I guess you installed the correct nsepy package. Follow the previous post in this issue if you didn't install the package yet. 
For me, it's working fine.

**Comment by sf99167** [comment] 2020-01-15 02:21
The code is good but once executed, it waits and waits with no response from NSE.. sometimes if I am lucky, I get a null dataframe.
I guess this is a NSE issue after all.
    On Wednesday, January 15, 2020, 12:25:30 AM GMT+5:30, Subinoy Biswas <notifications@github.com> wrote:  
 
 

import requestsimport bs4import pandas as pdimport scipy import lxmlimport numpy session = requests.Session()session.max_redirects = 60 from nsepy import get_historyfrom datetime import dateimport dateutil.relativedeltaimport matplotlib.pyplot as pltimport matplotlib ACCStock=get_history(symbol="ACC", start=date(2018,1,1),end=date(2018,1,10))print(ACCStock)


The code looking good to me. You didn't provide error what is coming with this code.

But I guess you installed the correct nsepy package. Follow the previous post in this issue if you didn't install the package yet.
For me, it's working fine.

**Comment by nikunjpurohit** [comment] 2020-01-15 04:32
Try on python 3.7 or 3.8

**Comment by naga2303** [comment] 2020-01-15 09:49
> One more for your knowledge....
> MY python code to fetch the data works till 5:00 pm. Then I get "ConnectionError - 10060"
> This is happening since tomorrow.

Yes i am also facing this issue ..i get data using selenium... Is this issue resolved??

**Comment by sf99167** [comment] 2020-01-15 12:02
@nikunjpurohit , am using Python 3.7.

**Comment by sf99167** [comment] 2020-01-15 12:10
> > import requestsimport bs4import pandas as pdimport scipy import lxmlimport numpy session = requests.Session()session.max_redirects = 60 from nsepy import get_historyfrom datetime import dateimport dateutil.relativedeltaimport matplotlib.pyplot as pltimport matplotlib ACCStock=get_history(symbol="ACC", start=date(2018,1,1),end=date(2018,1,10))print(ACCStock)
> 
> The code looking good to me. You didn't provide error what is coming with this code.
> 
> But I guess you installed the correct nsepy package. Follow the previous post in this issue if you didn't install the package yet.
> For me, it's working fine.

Are you able to download the data?

**Comment by subinoy** [comment] 2020-01-15 15:27
Symbol	Series	Prev Close	Open	High	Low	Last	Close	VWAP	Volume	Turnover	Trades	Deliverable Volume	%Deliverble
Date														
2020-01-01	ACC	EQ	1445.65	1452.5	1457.00	1438.20	1438.4	1440.10	1444.50	321092	4.638177e+13	12889	82053	0.2555
2020-01-02	ACC	EQ	1440.10	1442.0	1501.70	1442.00	1494.8	1493.05	1484.55	1503364	2.231817e+14	42586	394367	0.2623
2020-01-03	ACC	EQ	1493.05	1493.0	1494.00	1467.10	1476.8	1476.30	1478.78	568262	8.403368e+13	18109	146128	0.2571
2020-01-06	ACC	EQ	1476.30	1462.1	1469.85	1430.55	1433.0	1435.55	1445.74	408807	5.910282e+13	13675	147029	0.3597
2020-01-07	ACC	EQ	1435.55	1450.0	1465.05	1436.00	1453.1	1456.00	1452.32	863805	1.254521e+14	26295	223430	0.2587

**Comment by subinoy** [comment] 2020-01-15 15:29
For 2018 it's not working however, 2020 and 2019 it's working fine.
Change the date and try. Also rewrite the get_history line as I think the quote mark may be jhas problem in your script. 
I didn't try the "Session()session.max_redirects = 60" in yoyr code.
Hope things will work for you.
Best.

**Comment by Praxal** [comment] 2020-01-15 16:17
Thanks a lot @subinoy, This is working for me as well.

**Comment by sf99167** [comment] 2020-01-15 17:20
Are you able to download the data??
    On Wednesday, January 15, 2020, 09:47:03 PM GMT+5:30, Praxal Shah <notifications@github.com> wrote:  
 
 
Thanks a lot @subinoy, This is working for me as well.

**Comment by sf99167** [comment] 2020-01-15 17:22
> For 2018 it's not working however, 2020 and 2019 it's working fine.
> Change the date and try. Also, rewrite the get_history line as I think the quote mark may be has some problem in your script.
> I didn't try the "Session()session.max_redirects = 60" in your code.
> Hope things will work for you.
> Best.

thx, will try that

**Comment by sumedhj13** [comment] 2020-01-15 18:40
After running python setup.py install how to confirm that the changes have taken place? My old nsepy is at location "Anaconda3\Lib\site-packages\nsepy" do I need to save the new nsepy folder in the same location ?

**Comment by sf99167** [comment] 2020-01-16 02:43
> For 2018 it's not working however, 2020 and 2019 it's working fine.
> Change the date and try. Also, rewrite the get_history line as I think the quote mark may be has some problem in your script.
> I didn't try the "Session()session.max_redirects = 60" in your code.
> Hope things will work for you.
> Best.

Thx @subinoy , the historical data download works fine. Again thx for the pointer on the quote marks. 

However downloading option chain is a dead end I guess as that is blocked by NSE. Even excel power queries for option chain are hanging.

**Comment by adhish9899** [comment] 2020-01-19 06:04
Thank you @subinoy . NSEpy is working fine now.

**Comment by Veereshkumar4** [comment] 2020-01-19 08:22
> 
> 
> Thank you @subinoy . NSEpy is working fine now.

Hi.. can you please share the steps you took to get it to work?
thanks

**Comment by sf99167** [comment] 2020-01-20 11:53
Looks like NSE has restricted download of historical data as well. When I try my code, I only get till 17th December. I cannot get todays data.... will try again post 6 pm

**Comment by sf99167** [comment] 2020-01-20 12:04
https://www.nseindia.com/api/historical/cm/equity?symbol=ACC&series=[%22EQ%22]&from=20-01-2019&to=20-01-2020 ... this works but not the old nse site. Anyone else experiencing the same problem
??

**Comment by panda-balarka** [comment] 2020-01-20 15:54
Updated to the 314 tree, but getting OSError("(10060, "WSAETIMEDOUT')") error now. Is is the same with tou @sf99167 ?

**Comment by panda-balarka** [comment] 2020-01-20 16:11
To others who are facing the issue with OSError("(10060, "WSAETIMEDOUT')"). Try to delete the nsepy and nsepy-0.7.dist.info from the site-packages folder. (If a conda env is used for this, delete the directories in the respective env). Then do a fresh python setup.py install from the sources suggested by subinoy, i.e https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4 

@sf99167 : after this fresh install, I'm able to fetch data for today aswell. Working fine for historical data of equities.

**Comment by xerxys300** [comment] 2020-01-20 16:36
Dear All,
Sorry I haven't been able to catch up with the recent changes, I would request you guys to submit a pull request.

Thanks for keeping it alive.

**Comment by swapniljariwala** [comment] 2020-01-20 16:46
Hello All,

Apologies I've not been able to update this library. Request our savior to share a pull request.

Thanks for keeping this project alive.

Thanks
Swapnil

**Comment by sf99167** [comment] 2020-01-20 16:46
> To others who are facing the issue with OSError("(10060, "WSAETIMEDOUT')"). Try to delete the nsepy and nsepy-0.7.dist.info from the site-packages folder. (If a conda env is used for this, delete the directories in the respective env). Then do a fresh python setup.py install from the sources suggested by subinoy, i.e https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4
> 
> @sf99167 : after this fresh install, I'm able to fetch data for today aswell. Working fine for historical data of equities.

yes its working now. Noticed the glitch on the NSE website as well with respect to historical data. Uptil 5.45 pm it was only showing till 17th Jan 2020. Post 6 pm they rectified it.

**Comment by ghoshsudipto** [comment] 2020-01-24 20:21
I am getting this error
ImportError: cannot import name 'get_history' from 'nsepy' (C:\Users\Sudipto\Dropbox\Python\nsepy\__init__.py
can anyone help ?

**Comment by sf99167** [comment] 2020-01-25 03:41
If you can delete the nsepy subdirectory and re-install nsepy as per Subinoy's message it should sort out your problem.
Also, as Subinoy suggested, if you can share the code where you are facing the problem, we could help.. cos I sorted out my program problem that way 
    On Saturday, January 25, 2020, 01:51:43 AM GMT+5:30, Sudipto Ghosh <notifications@github.com> wrote:  
 
 
I am getting this error
ImportError: cannot import name 'get_history' from 'nsepy' (C:\Users\Sudipto\Dropbox\Python\nsepy_init_.py
can anyone help ?

**Comment by virender-thakur** [comment] 2020-01-27 11:43
> 
> 
> It is still not working.. 9th Jan 2020. Any one having a solution for this?
> Found a workaround for this...
> 
>     1. Backup existing urls.py program (file path = Python\Python37-32\Lib\site-packages\nsepy)
> 
>     2. Copy the attached urls.py and restart console/cmd.
> 
> 
> **Change the file extension to py instead of txt.**
> [urls.txt](https://github.com/swapniljariwala/nsepy/files/4045247/urls.txt)

Thanks dear its working after making a small change:

 i just adder user agent in header to avoid connection error



'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
}


[urls.txt](https://github.com/swapniljariwala/nsepy/files/4116906/urls.txt)

**Comment by vishaldamani** [comment] 2020-01-28 13:20
Can someone please help me how to solve this error

================ RESTART: D:\OneDrive\PythonPrograms\bhavcopy.py ===============
Traceback (most recent call last):
File "D:\OneDrive\PythonPrograms\bhavcopy.py", line 4, in
prices = get_price_list(date(2015,1,1))
File "C:\Program Files (x86)\Python38-32\lib\site-packages\nsepy\history.py", line 309, in get_price_list
txt = unzip_str(res.content)
File "C:\Program Files (x86)\Python38-32\lib\site-packages\nsepy\commons.py", line 122, in unzip_str
zf = zipfile.ZipFile(file=fp)
File "C:\Program Files (x86)\Python38-32\lib\zipfile.py", line 1267, in init
self._RealGetContents()
File "C:\Program Files (x86)\Python38-32\lib\zipfile.py", line 1334, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by subinoy** [comment] 2020-01-28 14:54
Could you post your code here? and as far as I know, Nsepy doesn't have a
function get_price_list.

Also, mention which version of python you are using and whether you have
installed the latest NSEpy. By looking at the error message it's
difficult to interpret what's wrong.

Although, there is a function get_history. Did you check with this function
whether your script is working or not?

Best,
Subinoy

**Comment by vishaldamani** [comment] 2020-01-28 18:38
Sir, I'm using python 3.7. After installing the latest nsepy from the link provided by you get_history function has started working again. Thanks a lot

To download bhavcopy I was using this code, Used to work earlier. but now some issue. Anyways its not so important. Nsepy other functions started working after your update. Thanks.

import csv
from nsepy.history import get_price_list
from datetime import date
prices = get_price_list(date(2015,1,1))
prices.to_csv('Bhavcopy.csv')

**Comment by subinoy** [comment] 2020-01-28 19:25
Glad to know it's working fine again.

By the way, I didn't provide any code. It's other people who contributed
and I just help others who faced the difficulties in installing and running
the code.

Best,
Subinoy

**Comment by sf99167** [comment] 2020-01-29 06:56
Hi Vishal
Nsepy requires some dependencies /libraries to be loaded. Have updated your code, please try it as it worked for me
import requestsimport bs4import pandas as pdimport scipy import lxmlimport numpyfrom datetime import datetimefrom datetime import dateimport dateutil.relativedelta
import csvfrom nsepy.history import get_price_listfrom datetime import dateprices = get_price_list(date(2020,1,28))prices.to_csv('Bhavcopy.csv')
regards
Sean
    On Wednesday, January 29, 2020, 12:08:01 AM GMT+5:30, vishaldamani <notifications@github.com> wrote:  
 
 
Sir, I'm using python 3.7. After installing the latest nsepy from the link provided by you get_history function has started working again. Thanks a lot

To download bhavcopy I was using this code, Used to work earlier. but now some issue. Anyways its not so important. Nsepy other functions started working after your update. Thanks.

import csv
from nsepy.history import get_price_list
from datetime import date
prices = get_price_list(date(2015,1,1))
prices.to_csv('Bhavcopy.csv')

**Comment by vishaldamani** [comment] 2020-01-29 08:53
Thanks. Your code worked.

**Comment by sf99167** [comment] 2020-01-29 09:35
Justed added on to your code... You're most welcome  :)
    On Wednesday, January 29, 2020, 02:23:29 PM GMT+5:30, vishaldamani <notifications@github.com> wrote:  
 
 
Thanks. Your code worked.

**Comment by harrystark** [comment] 2020-02-05 05:08
Hey Everyone
I messed up in the process. I used Subinoy's steps but extracted the contents in the wrong folder.
Is there some way I can completely uninstall this NSEpy library and redo the process. I tried to use- pip uninstall NSEpy but there is an error saying _"Cannot uninstall 'nsepy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall"_

**Comment by subinoy** [comment] 2020-02-05 06:25
Don'y worry about what you have done. Just issue the command "pip install
--upgrade nsepy" at your terminal without the quotes.

Best,
Subinoy

**Comment by sweetatyagiaz** [comment] 2020-02-05 11:37
> For 2018 it's not working however, 2020 and 2019 it's working fine.
> Change the date and try. Also, rewrite the get_history line as I think the quote mark may be has some problem in your script.
> I didn't try the "Session()session.max_redirects = 60" in your code.
> Hope things will work for you.
> Best.

Hi still not working I have used "session.max_redirects = 60" but still waiting. I dnot know why. Can you help?

**Comment by sf99167** [comment] 2020-02-05 12:40
Somehow they have blocked historical data.... same with option chain data
    On Wednesday, February 5, 2020, 05:07:34 PM GMT+5:30, Rakesh Ranjan <notifications@github.com> wrote:  
 
 

For 2018 it's not working however, 2020 and 2019 it's working fine.
Change the date and try. Also, rewrite the get_history line as I think the quote mark may be has some problem in your script.
I didn't try the "Session()session.max_redirects = 60" in your code.
Hope things will work for you.
Best.


Hi still not working I have used "session.max_redirects = 60" but still waiting. I dnot know why. Can you help?

**Comment by kapilaggr** [comment] 2020-02-11 02:40
Pls advise. I am facing following error after completing the above steps:

    from nsepy import get_history
ImportError: cannot import name 'get_history' from 'nsepy' (C:\Users\KA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy\__init__.py)

Process finished with exit code 1

These are the relevant lines of the code I am using:

from nsepy import get_history

pairdata=pd.read_excel(r'C:\Users\KA\Desktop\Trading & Investment\Algo Trading\live\pairtrade\Code1_Input.xlsx')

s1= get_history(symbol=pairdata.at[i,'symbol1'],start=date(2017,1,1),end=date.today())
    s2= get_history(symbol=pairdata.at[i,'symbol2'],start=date(2017,1,1),end=date.today())

**Comment by sf99167** [comment] 2020-02-11 03:40
Can you post the complete code??
Cos there are dependencies to load alongwith NSEpy.. like Numpy, Scipy, lxml etc....
    On Tuesday, February 11, 2020, 08:10:22 AM GMT+5:30, kapilaggr <notifications@github.com> wrote:  
 
 
Pls advise. I am facing following error after completing the above steps:
from nsepy import get_history

ImportError: cannot import name 'get_history' from 'nsepy' (C:\Users\KA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy_init_.py)

Process finished with exit code 1

These are the relevant lines of the code I am using:

from nsepy import get_history

pairdata=pd.read_excel(r'C:\Users\KA\Desktop\Trading & Investment\Algo Trading\live\pairtrade\Code1_Input.xlsx')

s1= get_history(symbol=pairdata.at[i,'symbol1'],start=date(2017,1,1),end=date.today())
s2= get_history(symbol=pairdata.at[i,'symbol2'],start=date(2017,1,1),end=date.today())

**Comment by kapilaggr** [comment] 2020-02-11 17:00
> Can you post the complete code?? Cos there are dependencies to load alongwith NSEpy.. like Numpy, Scipy, lxml etc.... On Tuesday, February 11, 2020, 08:10:22 AM GMT+5:30, kapilaggr <notifications@github.com> wrote: Pls advise. I am facing following error after completing the above steps: from nsepy import get_history ImportError: cannot import name 'get_history' from 'nsepy' (C:\Users\KA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy_init_.py) Process finished with exit code 1 These are the relevant lines of the code I am using: from nsepy import get_history pairdata=pd.read_excel(r'C:\Users\KA\Desktop\Trading & Investment\Algo Trading\live\pairtrade\Code1_Input.xlsx') s1= get_history(symbol=pairdata.at[i,'symbol1'],start=date(2017,1,1),end=date.today()) s2= get_history(symbol=pairdata.at[i,'symbol2'],start=date(2017,1,1),end=date.today()) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

from nsepy import get_history
from datetime import date, datetime, timedelta
import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.formula.api as sm
import scipy, scipy.stats
import statsmodels.regression.linear_model as lm
from math import sqrt
from math import ceil
from statsmodels.tsa.stattools import adfuller
from statsmodels.api import add_constant
from statsmodels.tsa.vector_ar.vecm import coint_johansen
from statistics import mean
import openpyxl
import xlrd
from openpyxl.styles import PatternFill
import time
from pandas_datareader import data as pdr
import yfinance as yf

pairdata=pd.read_excel(r'C:\Users\KA\Desktop\Code1_Input.xlsx')
for i in pairdata.index:
    try:
        print(i)
        s1 = get_history(symbol=pairdata.at[i, 'symbol1'], start=date(2017, 1, 1), end=date.today())
        s2 = get_history(symbol=pairdata.at[i, 'symbol2'], start=date(2017, 1, 1), end=date.today())
        symbol1 = s1[['Symbol', 'Close']]
        symbol2 = s2[['Symbol', 'Close']]
        combined_data = pd.merge(symbol1, symbol2, on='Date', how='outer')
        print(combined_data)
__________________________________________
hope this helps

**Comment by kapilaggr** [comment] 2020-02-11 17:02
> > Can you post the complete code?? Cos there are dependencies to load alongwith NSEpy.. like Numpy, Scipy, lxml etc.... On Tuesday, February 11, 2020, 08:10:22 AM GMT+5:30, kapilaggr [notifications@github.com](mailto:notifications@github.com) wrote: Pls advise. I am facing following error after completing the above steps: from nsepy import get_history ImportError: cannot import name 'get_history' from 'nsepy' (C:\Users\KA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy_init_.py) Process finished with exit code 1 These are the relevant lines of the code I am using: from nsepy import get_history pairdata=pd.read_excel(r'C:\Users\KA\Desktop\Trading & Investment\Algo Trading\live\pairtrade\Code1_Input.xlsx') s1= get_history(symbol=pairdata.at[i,'symbol1'],start=date(2017,1,1),end=date.today()) s2= get_history(symbol=pairdata.at[i,'symbol2'],start=date(2017,1,1),end=date.today()) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> from nsepy import get_history
> from datetime import date, datetime, timedelta
> import pandas as pd
> import requests
> import numpy as np
> import matplotlib.pyplot as plt
> import seaborn as sns
> sns.set(style="whitegrid")
> from sklearn.linear_model import LinearRegression
> from sklearn.metrics import mean_squared_error, r2_score
> import statsmodels.formula.api as sm
> import scipy, scipy.stats
> import statsmodels.regression.linear_model as lm
> from math import sqrt
> from math import ceil
> from statsmodels.tsa.stattools import adfuller
> from statsmodels.api import add_constant
> from statsmodels.tsa.vector_ar.vecm import coint_johansen
> from statistics import mean
> import openpyxl
> import xlrd
> from openpyxl.styles import PatternFill
> import time
> from pandas_datareader import data as pdr
> import yfinance as yf
> 
> pairdata=pd.read_excel(r'C:\Users\KA\Desktop\Code1_Input.xlsx')
> for i in pairdata.index:
> try:
> print(i)
> s1 = get_history(symbol=pairdata.at[i, 'symbol1'], start=date(2017, 1, 1), end=date.today())
> s2 = get_history(symbol=pairdata.at[i, 'symbol2'], start=date(2017, 1, 1), end=date.today())
> symbol1 = s1[['Symbol', 'Close']]
> symbol2 = s2[['Symbol', 'Close']]
> combined_data = pd.merge(symbol1, symbol2, on='Date', how='outer')
> print(combined_data)
> 
> hope this helps

btw same thing (code + nsepy) is working on another colleague's computer but not mine.

**Comment by kapilaggr** [comment] 2020-02-12 16:45
any suggestions??

**Comment by sf99167** [comment] 2020-02-12 17:44
Actually yes...  As pointed out by Subinoy some time ago when I wanted to retrieve older historical data, we realised that NSE has blocked off that data.....
s1 = get_history(symbol=pairdata.at[i, 'symbol1'], start=date(2017, 1, 1), end=date.today())
s2 = get_history(symbol=pairdata.at[i, 'symbol2'], start=date(2017, 1, 1), end=date.today())
try changing it to 2019 instead of 2017 and check if it works... cos even 2018 does not work with my code....
Do let us know


    On Wednesday, February 12, 2020, 10:15:07 PM GMT+5:30, kapilaggr <notifications@github.com> wrote:  
 
 
any suggestions??

**Comment by kapilaggr** [comment] 2020-02-12 17:54
> Actually yes...  As pointed out by Subinoy some time ago when I wanted to retrieve older historical data, we realised that NSE has blocked off that data..... s1 = get_history(symbol=pairdata.at[i, 'symbol1'], start=date(2017, 1, 1), end=date.today()) s2 = get_history(symbol=pairdata.at[i, 'symbol2'], start=date(2017, 1, 1), end=date.today()) try changing it to 2019 instead of 2017 and check if it works... cos even 2018 does not work with my code.... Do let us know On Wednesday, February 12, 2020, 10:15:07 PM GMT+5:30, kapilaggr <notifications@github.com> wrote: any suggestions?? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

2017 is working whn same code + nsepy files are run on a colleague's config...so that ma not be the reason

**Comment by sf99167** [comment] 2020-02-12 17:56
can you also send the excel file so that a complete test can be run... 
    On Wednesday, February 12, 2020, 11:24:15 PM GMT+5:30, kapilaggr <notifications@github.com> wrote:  
 
 

Actually yes...  As pointed out by Subinoy some time ago when I wanted to retrieve older historical data, we realised that NSE has blocked off that data..... s1 = get_history(symbol=pairdata.at[i, 'symbol1'], start=date(2017, 1, 1), end=date.today()) s2 = get_history(symbol=pairdata.at[i, 'symbol2'], start=date(2017, 1, 1), end=date.today()) try changing it to 2019 instead of 2017 and check if it works... cos even 2018 does not work with my code.... Do let us know On Wednesday, February 12, 2020, 10:15:07 PM GMT+5:30, kapilaggr notifications@github.com wrote: any suggestions?? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


2017 is working whn same code + nsepy files are run on a colleague's config...so that ma not be the reason

**Comment by kundan174** [comment] 2020-04-21 04:48
Anyone using AWS machine to pull data via nsepy??
I am not able to pull any data from AWS linux machine via nsepy, it doesn't through any error but stucks after giving command to pull data.
![NSEPY](https://user-images.githubusercontent.com/54245101/79826431-549d3a00-83b9-11ea-9e90-237b80067726.JPG)

**Comment by subinoy** [comment] 2020-04-21 05:02
I think it’s more of a permissions issue.

**Comment by kundan174** [comment] 2020-04-21 05:05
do you mean AWS is not allowing?
I have configured inbound and outbound rules from any any on both sides.

**Comment by Mananssl01** [comment] 2020-04-21 05:25
since last week , i m also facing issues while extraction data.
it gets loaded , but sometimes , future data gives [ ], sometimes cash Data
gives [ ], etc.. didn't faced this problem earlier. and all data was loaded.
Looks like NSE is moving towards limited support to old website.
I m saying this because , if u want to see futures data of some stock for
say , 28 may expiry , you will not get this option itself in dropdown. In
this case , i need t download the bhavcopy. Just a thought/observation !!

**Comment by subinoy** [comment] 2020-04-21 05:25
If you can access from your machine but not from AWS then it’s indicate AWS
is not able to reach NSE. I don’t see it’s a NSE site problem. Some network
specialists may shed more light on this.

**Comment by Mananssl01** [comment] 2020-04-21 05:31
No Swapnil ,
 I am not using AWS but normal API call from my machine. Lately , i am
facing some issues..need to retry 3-4 times to check before invoking actual
code.
If its smooth for u , then may be network issue in my area.

**Comment by kundan174** [comment] 2020-04-21 05:36
In my local machine everything works fine.
Can you please share me your piece of code will try same from my machine.

**Comment by Mananssl01** [comment] 2020-04-21 05:38
Sure , I'll ..Currently connected to office laptop ...:)

**Comment by panda-balarka** [comment] 2020-04-27 14:11
> Anyone using AWS machine to pull data via nsepy??
> I am not able to pull any data from AWS linux machine via nsepy, it doesn't through any error but stucks after giving command to pull data.
> ![NSEPY](https://user-images.githubusercontent.com/54245101/79826431-549d3a00-83b9-11ea-9e90-237b80067726.JPG)

I think this is because of AWS proxies... What I have observed is NSE does not allow requests for data when the channel is outside India or its a known traceable local IP... The issue is similar if try to run your code on your local PC but with a VPN turned on...the request is stuck until default timeout period from the requests library.

**Comment by sf99167** [comment] 2020-04-27 15:56
Historical data is always an issue, if you change the start date to 2019,1,1 and end to 2020,4,27 it will pull the data...
anything over two years old is an issue
    On Monday, April 27, 2020, 07:42:02 PM GMT+5:30, bALarkA <notifications@github.com> wrote:  
 
 



Anyone using AWS machine to pull data via nsepy??
I am not able to pull any data from AWS linux machine via nsepy, it doesn't through any error but stucks after giving command to pull data.



I think this is because of AWS proxies... What I have observed is NSE does not allow requests for data when the channel is outside India or its a known traceable local IP... The issue is similar if try to run your code on your local PC but with a VPN turned on...the request is stuck until default timeout period from the requests library.

**Closed** 2020-06-28 03:23 UTC

**Comment by richie-1** [comment] 2020-10-30 22:29
Hi, 
I am facing a similar issue. When I run nsepy on my machine, it works brilliantly but when I run it on Google Colab the get_history keeps running. My code is as follows

import pandas as pd
import numpy as np
from datetime import date
import matplotlib.pyplot as plt
pip install nsepy

from nsepy import get_history
tcs = get_history(symbol='TCS',
                    start=date(2015,1,1),
                    end=date(2016,12,31))

@sf99167 Is it because of the same reason you've mentioned it in the previous thread?
@subinoy is it a permission issue? have you ever tried running this on Google Colab?
